name: Update Card Names Catalog
on:
  schedule:
    - cron: 0 0 * * SUN
     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: https://api.scryfall.com/catalog/card-names
          configuration: '{ "method": "GET"}'
          save-location: assets/
          save-name: card-names

      - name: Build and Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: assets # Saves the data into the 'data' directory on the main branch.
