name: Update Atomic Catalog Alternate
on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/StandardAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: StandardAtomic
          set-output: false

      - name: Build and Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # Pushes the updates to the main branch.
          folder: assets # The location of the data.json file saved by the Fetch API Data action.
          target-folder: asset # Saves the data into the 'data' directory on the main branch.
