name: Update Card Catalog
on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:
jobs:
  update-card-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run Card Catalog Update
        run: bash ./update-card-catalog.sh

      - name: Build and Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # Pushes the updates to the gh-pages branch.
          folder: assets # The location of the json files saved by the Fetch API Data action.
          target-folder: assets # Saves the data into the 'assets' directory on the gh-pages branch.
