name: Update Atomic Catalog
on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/StandardAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: StandardAtomic
          set-output: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/PauperAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: PauperAtomic
          set-output: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/PioneerAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: PioneerAtomic
          set-output: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/ModernAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: ModernAtomic
          set-output: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/LegacyAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: LegacyAtomic
          set-output: false

      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: https://mtgjson.com/api/v5/VintageAtomic.json
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: VintageAtomic
          set-output: false

      - name: Build and Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # Pushes the updates to the gh-pages branch.
          folder: assets # The location of the json files saved by the Fetch API Data action.
          target-folder: assets # Saves the data into the 'assets' directory on the gh-pages branch.
